export const DEFAULT_ARENA_KEY = "classic";

export const ARENA_CONFIGS = {
  classic: {
    label: "Classic",
    hint: "Balanced ruleset with clean floor and no wind.",
    gravity: -14,
    floorFriction: 0.36,
    floorRestitution: 0.52,
    lowerFriction: 0.13,
    lowerRestitution: 0.7,
    lowerDensity: 0.26,
    upperFriction: 0.75,
    upperRestitution: 0.52,
    upperDensity: 2.7,
    wind: { x: 0, z: 0, pulse: 0, freq: 0 },
    obstacles: [],
  },
  bumperGarden: {
    label: "Bumper Garden",
    hint: "Bouncy pegs near center boost energy transfer on contact.",
    gravity: -15,
    floorFriction: 0.34,
    floorRestitution: 0.6,
    lowerFriction: 0.1,
    lowerRestitution: 0.76,
    lowerDensity: 0.24,
    upperFriction: 0.7,
    upperRestitution: 0.6,
    upperDensity: 2.85,
    wind: { x: 0, z: 0, pulse: 0, freq: 0 },
    obstacles: [
      {
        type: "cyl",
        x: 2.4,
        y: 0.55,
        z: 0.9,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: -2.6,
        y: 0.55,
        z: -1.2,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: 0.5,
        y: 0.55,
        z: -2.8,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: -0.7,
        y: 0.55,
        z: 2.7,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
    ],
  },
  edgeBox: {
    label: "Edge Box",
    hint: "Center box with lower cap starting half-out from the box edge.",
    gravity: -14.5,
    floorFriction: 0.35,
    floorRestitution: 0.56,
    lowerFriction: 0.12,
    lowerRestitution: 0.72,
    lowerDensity: 0.25,
    upperFriction: 0.73,
    upperRestitution: 0.56,
    upperDensity: 2.78,
    wind: { x: 0, z: 0, pulse: 0, freq: 0 },
    lowerStart: { x: 1.32, z: 0 },
    lowerStartY: 1.152,
    obstacles: [
      {
        type: "box",
        x: 0,
        y: 0.66,
        z: 0,
        hx: 1.35,
        hy: 0.42,
        hz: 1.35,
        color: "#b58f63",
        friction: 0.38,
        restitution: 0.42,
      },
    ],
  },
};
