export const DEFAULT_ARENA_KEY = "classic";

export const ARENA_CONFIGS = {
  classic: {
    label: "Classic",
    hint: "Balanced ruleset with clean floor and no wind.",
    gravity: -14,
    floorFriction: 0.36,
    floorRestitution: 0.52,
    lowerFriction: 0.18,
    lowerRestitution: 0.66,
    lowerDensity: 0.32,
    upperFriction: 0.75,
    upperRestitution: 0.52,
    upperDensity: 2.7,
    wind: { x: 0, z: 0, pulse: 0, freq: 0 },
    obstacles: [],
  },
  windTunnel: {
    label: "Wind Tunnel",
    hint: "Crosswind pulses every second and shoves both discs around.",
    gravity: -13,
    floorFriction: 0.35,
    floorRestitution: 0.55,
    lowerFriction: 0.16,
    lowerRestitution: 0.68,
    lowerDensity: 0.31,
    upperFriction: 0.72,
    upperRestitution: 0.56,
    upperDensity: 2.75,
    wind: { x: 20, z: 2, pulse: 16, freq: 1.5 },
    obstacles: [
      {
        type: "box",
        x: -5.6,
        y: 0.42,
        z: 0,
        hx: 0.35,
        hy: 0.35,
        hz: 2.9,
        color: "#2a4365",
        friction: 0.7,
        restitution: 0.45,
      },
      {
        type: "box",
        x: 5.6,
        y: 0.42,
        z: 0,
        hx: 0.35,
        hy: 0.35,
        hz: 2.9,
        color: "#2a4365",
        friction: 0.7,
        restitution: 0.45,
      },
    ],
  },
  bumperGarden: {
    label: "Bumper Garden",
    hint: "Bouncy pegs near center boost spin transfers on contact.",
    gravity: -15,
    floorFriction: 0.34,
    floorRestitution: 0.6,
    lowerFriction: 0.14,
    lowerRestitution: 0.72,
    lowerDensity: 0.3,
    upperFriction: 0.7,
    upperRestitution: 0.6,
    upperDensity: 2.85,
    wind: { x: 0, z: 0, pulse: 0, freq: 0 },
    obstacles: [
      {
        type: "cyl",
        x: 2.4,
        y: 0.55,
        z: 0.9,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: -2.6,
        y: 0.55,
        z: -1.2,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: 0.5,
        y: 0.55,
        z: -2.8,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
      {
        type: "cyl",
        x: -0.7,
        y: 0.55,
        z: 2.7,
        r: 0.58,
        hh: 0.45,
        color: "#7f9cf5",
        friction: 0.25,
        restitution: 0.9,
      },
    ],
  },
  iceDrift: {
    label: "Ice Drift",
    hint: "Low-friction floor with gentle drifting wind and long slides.",
    gravity: -11.5,
    floorFriction: 0.05,
    floorRestitution: 0.5,
    lowerFriction: 0.04,
    lowerRestitution: 0.62,
    lowerDensity: 0.29,
    upperFriction: 0.22,
    upperRestitution: 0.5,
    upperDensity: 2.6,
    wind: { x: -8, z: 10, pulse: 6, freq: 0.8 },
    obstacles: [
      {
        type: "box",
        x: -3.8,
        y: 0.31,
        z: 3.2,
        hx: 1.8,
        hy: 0.12,
        hz: 0.5,
        color: "#63b3ed",
        friction: 0.15,
        restitution: 0.45,
      },
      {
        type: "box",
        x: 3.8,
        y: 0.31,
        z: -3.1,
        hx: 1.8,
        hy: 0.12,
        hz: 0.5,
        color: "#63b3ed",
        friction: 0.15,
        restitution: 0.45,
      },
    ],
  },
};
